[build]
target = "riscv32im-risc0-zkvm-elf"

[target.riscv32im-risc0-zkvm-elf]
rustflags = ["-Cpasses=loweratomic", "-Ctarget-feature=-a,-c"]

[unstable]
build-std = ["core", "alloc"]
build-std-features = []